name: 'Build Infrastructure'
on:
  push:
    branches: ["main"]
  pull_request:
    
permissions: 
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
    defaults:
      run:
        working-directory: ./terraform
        shell: bash
          
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Azure Login'
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDS}}

        # run: az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET)  --tenant $(ARM_TENANT_ID)
      - name: 'Install Terraform'
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.3.6
      
      - name: 'Terraform Init'
        run: terraform init -backend-config=environments/dev/backend.tfvars

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: 'Terraform Plan'
        run: |
            terraform plan -var-file=environments/dev/variables.tfvars -out=.terraform/plan.out
      
      - name: Terraform Apply
        run: terraform apply .terraform/plan.out